from __future__ import annotations

from typing import Protocol

from onedep_lib.enums import ExperimentType
from onedep_lib.session.models import LocalFile, LocalSession


class SessionStore(Protocol):
    def create_session(self, session: LocalSession) -> None: ...
    def get_session(self) -> LocalSession: ...
    def update_experiment_type(self, experiment_type: ExperimentType) -> None: ...
    def update_em_params(self, em_subtype: str | None, coordinates: bool | None) -> None: ...
    def set_remote_dep_id(self, dep_id: str) -> None: ...
    def add_file(self, file: LocalFile) -> None: ...
    def remove_file(self, file_id: str) -> None: ...
    def get_file(self, file_id: str) -> LocalFile: ...
    def get_all_files(self) -> list[LocalFile]: ...
    def set_voxel_values(
        self,
        file_id: str,
        spacing_x: float,
        spacing_y: float,
        spacing_z: float,
        contour: float,
    ) -> None: ...
    def close(self) -> None: ...
